const {chromium,devices}=require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/playwright');
const assert=require('node:assert/strict');const fs=require('node:fs/promises');
(async()=>{
const browser=await chromium.launch({headless:true,args:['--no-sandbox']});const context=await browser.newContext({viewport:{width:1440,height:1000},permissions:['clipboard-read','clipboard-write'],acceptDownloads:true});const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));const base='http://127.0.0.1:8080/quick-phrase/';await page.goto(base);await page.locator('.phrase-card').first().waitFor();assert.equal(await page.locator('.phrase-card').count(),7);await page.locator('#offline-status').filter({hasText:'オフラインで使用できます'}).waitFor();await page.screenshot({path:'tests/desktop.png',fullPage:true});
await page.getByRole('button',{name:'コピー：詳しく整理',exact:true}).click();assert.equal(await page.evaluate(()=>navigator.clipboard.readText()),'以上の内容を、重要な情報を省略せず詳しく整理して。');await page.waitForFunction(async()=>{const {transact}=await import('./db.js');return(await transact()).phrases.find(p=>p.title==='詳しく整理').useCount===1;});
const longText='  長い本文\n'+('テスト 🌱 <script>alert(1)</script>\n'.repeat(200))+'  ';
await page.locator('#add').click();await page.locator('#phrase-title').fill('検証フレーズ');await page.locator('#phrase-text').fill(longText);await page.locator('#phrase-memo').fill('メモ専用検索');await page.locator('#phrase-icon').fill('🌱');await page.locator('#phrase-pinned').check();await page.locator('#phrase-form button[type=submit]').click();await page.locator('#phrase-dialog').waitFor({state:'hidden'});await page.reload();await page.getByRole('button',{name:'コピー：検証フレーズ',exact:true}).waitFor();await page.getByRole('button',{name:'コピー：検証フレーズ',exact:true}).click();assert.equal(await page.evaluate(()=>navigator.clipboard.readText()),longText);assert.equal(await page.locator('script').count(),1);
await page.locator('#search').fill('メモ専用検索');assert.equal(await page.locator('.phrase-card').count(),1);await page.locator('#search').fill('');
await page.getByRole('button',{name:'本文プレビュー：検証フレーズ',exact:true}).click();assert.equal(await page.locator('#preview-text').textContent(),longText);await page.locator('#preview-edit').click();await page.locator('#phrase-title').fill('編集済み');await page.locator('#phrase-form button[type=submit]').click();await page.locator('#phrase-dialog').waitFor({state:'hidden'});
await page.locator('#edit-mode').click();let titles=await page.locator('.section').first().locator('.phrase-title').allTextContents();assert.equal(titles.at(-1),'編集済み');await page.getByRole('button',{name:'編集済み：↑',exact:true}).click();await page.waitForFunction(()=>[...document.querySelectorAll('.section:first-child .phrase-title')].at(-2)?.textContent==='編集済み');await page.locator('#edit-mode').click();
await page.locator('#categories-open').click();await page.locator('#category-new').fill('新カテゴリ');await page.locator('#category-add-form button').click();await page.getByRole('textbox',{name:'新カテゴリの名前',exact:true}).waitFor();await page.getByRole('textbox',{name:'新カテゴリの名前',exact:true}).fill('改名カテゴリ');await page.getByRole('button',{name:'新カテゴリ：保存',exact:true}).click();await page.getByRole('textbox',{name:'改名カテゴリの名前',exact:true}).waitFor();await page.getByRole('button',{name:'改名カテゴリ：↑',exact:true}).click();await page.locator('#categories-dialog [data-close]').click();
await page.locator('#add').click();await page.locator('#phrase-title').fill('カテゴリ用');await page.locator('#phrase-text').fill('カテゴリテスト');await page.locator('#phrase-category').selectOption({label:'改名カテゴリ'});await page.locator('#phrase-form button[type=submit]').click();await page.locator('#phrase-dialog').waitFor({state:'hidden'});await page.locator('#tabs').getByRole('button',{name:'改名カテゴリ',exact:true}).click();assert.equal(await page.locator('.phrase-card').count(),1);await page.locator('#categories-open').click();await page.getByRole('button',{name:'改名カテゴリ：削除',exact:true}).click();await page.locator('#confirm-yes').click();await page.getByRole('textbox',{name:'改名カテゴリの名前',exact:true}).waitFor({state:'hidden'});await page.locator('#categories-dialog [data-close]').click();await page.locator('#tabs').getByRole('button',{name:'未分類',exact:true}).click();assert.equal(await page.locator('.phrase-card').count(),2);await page.locator('#tabs').getByRole('button',{name:'すべて',exact:true}).click();
await page.locator('#settings-open').click();await page.locator('#theme').selectOption('dark');await page.waitForFunction(()=>document.documentElement.dataset.theme==='dark');await page.locator('#settings-dialog [data-close]').click();await page.screenshot({path:'tests/dark.png',fullPage:true});await page.locator('#settings-open').click();await page.locator('#theme').selectOption('light');
let downloadP=page.waitForEvent('download');await page.locator('#export').click();const download=await downloadP;await download.saveAs('tests/backup.json');const backup=JSON.parse(await fs.readFile('tests/backup.json','utf8'));assert.equal(backup.phrases.length,9);assert(backup.phrases.some(p=>p.title==='編集済み'&&p.text===longText));
await page.locator('#import').setInputFiles({name:'bad.json',mimeType:'application/json',buffer:Buffer.from('{bad')});await page.locator('#toast').filter({hasText:'読み込めませんでした'}).waitFor();const invalid={...backup,phrases:[{...backup.phrases[0],useCount:-1}]};await page.locator('#import').setInputFiles({name:'invalid.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(invalid))});await page.locator('#toast').filter({hasText:'対応していない'}).waitFor();assert.equal(await page.locator('.phrase-card').count(),9);
await page.locator('#import').setInputFiles('tests/backup.json');await page.locator('#settings-dialog').waitFor({state:'hidden'});assert.equal(await page.locator('.phrase-card').count(),18);
await page.locator('#settings-open').click();await page.locator('input[value=replace]').check();await page.locator('#import').setInputFiles('tests/backup.json');await page.locator('#confirm-no').click();assert.equal(await page.locator('.phrase-card').count(),18);await page.locator('#import').setInputFiles('tests/backup.json');await page.locator('#confirm-yes').click();await page.locator('#settings-dialog').waitFor({state:'hidden'});assert.equal(await page.locator('.phrase-card').count(),9);
// Transaction abort must leave original data intact.
const rollback=await page.evaluate(async()=>{const {transact}=await import('./db.js');const before=await transact();try{await transact(s=>{s.phrases=[];throw Error('forced failure');});}catch{}return (await transact()).phrases.length===before.phrases.length;});assert(rollback);
// Cross-tab concurrent writes preserve both edits and propagate.
const second=await context.newPage();await second.goto(base);await second.locator('.phrase-card').first().waitFor();const addInTab=async(p,title)=>{await p.locator('#add').click();await p.locator('#phrase-title').fill(title);await p.locator('#phrase-text').fill(title);await p.locator('#phrase-form button[type=submit]').click();await p.locator('#phrase-dialog').waitFor({state:'hidden'});};await Promise.all([addInTab(page,'タブA'),addInTab(second,'タブB')]);await page.getByRole('button',{name:'コピー：タブB',exact:true}).waitFor();await second.getByRole('button',{name:'コピー：タブA',exact:true}).waitFor();await second.close();
await page.evaluate(()=>{navigator.clipboard.writeText=async()=>{throw Error('denied');};});await page.getByRole('button',{name:'コピー：詳しく整理',exact:true}).click();await page.locator('#toast').filter({hasText:'コピーできませんでした'}).waitFor();
// Offline launch and editing against the cached app.
await page.reload();await page.locator('.phrase-card').first().waitFor();await context.setOffline(true);await page.reload();await page.getByRole('button',{name:'コピー：タブA',exact:true}).waitFor();await addInTab(page,'オフライン追加');await page.reload();await page.getByRole('button',{name:'コピー：オフライン追加',exact:true}).waitFor();await page.locator('#settings-open').click();downloadP=page.waitForEvent('download');await page.locator('#export').click();await (await downloadP).saveAs('tests/offline-backup.json');await page.locator('#settings-dialog [data-close]').click();await context.setOffline(false);
// Deletion and clear persist, without samples reappearing.
await page.getByRole('button',{name:'本文プレビュー：オフライン追加',exact:true}).click();await page.locator('#preview-edit').click();await page.locator('#phrase-delete').click();await page.locator('#confirm-yes').click();await page.locator('#phrase-dialog').waitFor({state:'hidden'});await page.getByRole('button',{name:'コピー：オフライン追加',exact:true}).waitFor({state:'hidden'});
await page.locator('#settings-open').click();await page.locator('#clear').click();await page.locator('#confirm-yes').click();await page.locator('#settings-dialog').waitFor({state:'hidden'});await page.reload();await page.locator('#empty').waitFor({state:'visible'});assert.equal(await page.locator('.phrase-card').count(),0);assert.equal(errors.length,0,errors.join('\n'));
const mobile=await browser.newContext({...devices['Pixel 7'],permissions:['clipboard-read','clipboard-write']});const mp=await mobile.newPage();const mobileErrors=[];mp.on('pageerror',e=>mobileErrors.push(e.message));await mp.goto(base);await mp.locator('.phrase-card').first().waitFor();await mp.screenshot({path:'tests/mobile.png',fullPage:true});assert(await mp.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth));await mp.getByRole('button',{name:'コピー：詳しく整理',exact:true}).tap();assert.equal(await mp.evaluate(()=>navigator.clipboard.readText()),'以上の内容を、重要な情報を省略せず詳しく整理して。');await mp.locator('#add').tap();await mp.locator('#phrase-title').fill('スマホ登録');await mp.locator('#phrase-text').fill('スマホ本文');await mp.locator('#phrase-form button[type=submit]').tap();await mp.locator('#phrase-dialog').waitFor({state:'hidden'});await mp.reload();await mp.getByRole('button',{name:'コピー：スマホ登録',exact:true}).waitFor();await mp.locator('#settings-open').tap();assert(await mp.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth));await mp.screenshot({path:'tests/mobile-settings.png',fullPage:true});assert.equal(mobileErrors.length,0);
const manifest=JSON.parse(await fs.readFile('quick-phrase/manifest.json','utf8'));assert.equal(manifest.display,'standalone');assert.equal(manifest.scope,'./');
await browser.close();console.log('PASS: desktop CRUD, real clipboard, long text/XSS-safe display, search, pin/order, category CRUD, themes, export, invalid import, append/replace/cancel, atomic rollback, cross-tab writes, clipboard rejection, offline reload/create/export, deletion/clear persistence, Android viewport/touch, manifest.');
})().catch(e=>{console.error(e);process.exit(1);});
